name: GenerateLatest

on:
  push:
    branches: [ master ]

jobs:      
  deploy:
      runs-on: ubuntu-20.04
      concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
      steps:
        - uses: actions/checkout@v2
        
        - name: Copy Files
          run: | 
              ls -1d *.*/openapi.json | tail -n 1 | xargs -I % cp % latest/openapi.json
            
        - name: Publish Code
          run: |
              git config --local user.email "github-actions@github.com"
              git config --local user.name "github-actions"
              git add .
              git commit -m "🚀 Build latest docs" -a
              git push -f
